### ISSUE TITLE
Please add a SECURITY.md

### ISSUE THREAD

**Issue by mechaneus** [sunlight-cms/sunlight-cms#107]
Hello!

I found a potential issue, which I would like to share with you.
 Could you please add a SECURITY.md file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Thanks in advance.

**Comment by Shira-3749** [comment]
Sure, I've added a SECURITY.rst file.
