### ISSUE TITLE
Lépe reagovat na adresáře bez práva zápisu

### ISSUE THREAD

**Issue by Vitexus** [sunlight-cms/sunlight-cms#42]
Instalátor "spadne" pokud nemůže někam zapisovat.

Lepší by bylo oznámit nezapisovatelné složky s nějakým tlačítkem "zkusit znovu"

CopyPaste chmod/chown příklad by byl už jenom třešínka na dortu.

**Comment by ShiraNai7** [comment]
Instalátor by měl zapisovat pouze `config.php`. Kontrolu adresářů řeší `SystemChecker` a ten vypisuje konkrétní adresáře, se kterými je problém. Máš nějakou konkrétní chybovou hlášku?

**Comment by Vitexus** [comment]
![obrazek](https://user-images.githubusercontent.com/2621130/119221204-78680d80-baee-11eb-8f3a-dcf2a1c726d8.png)

**Comment by ShiraNai7** [comment]
c495acb
