### ISSUE TITLE
Links in the last installation step point to install subdirectory

### ISSUE THREAD

**Issue by koca2000** [sunlight-cms/sunlight-cms#64]
When you click the `open the website` link in the last step of the installation wizard you are redirected to `<site-url>/install/` instead of `<site-url>/`.

https://github.com/sunlight-cms/sunlight-cms/blob/2ce78999b69c2b3807c8cc5936626c43aa7fb4f8/install/index.php#L1175

SunLight CMS version: 8.0.0 git (https://github.com/sunlight-cms/sunlight-cms/commit/2ce78999b69c2b3807c8cc5936626c43aa7fb4f8)

**Comment by jDanek** [comment]
This works correctly on the XAMPP server.
![scr_1](https://user-images.githubusercontent.com/1703182/149824026-d008b175-ae70-45c9-9781-e9e44d9b42c1.png)
.

**Comment by koca2000** [comment]
I see. The issue is not what I though it is. My url of the site is the root directory of the server (Apache). In this case the link is blank instead of `/`. Administration link works fine.

![obrazek](https://user-images.githubusercontent.com/18701595/149824530-edad9f04-5e4a-4e24-a2ad-98fecc6a0506.png)

**Comment by jDanek** [comment]
Sorry misclicked

**Comment by ShiraNai7** [comment]
862342b913665ce4d3a281ea969e558dad6ff4fa
