### ISSUE TITLE
Replace realpath in Router::file method

### ISSUE THREAD

**Issue by koca2000** [sunlight-cms/sunlight-cms#75]
`Router::file` method uses `realpath` method to convert relative paths to absolute paths. However, since the `realpath` method only works with files that exist, the `Router::file` method doesn't work as expected in several cases.

Example:

In `img` hcm module: if the image doesn't exist, `img` `src` is `#` because url of error image is `./system/image_error.png?r=not-found` which is not a valid file path.

**Comment by ShiraNai7** [comment]
`realpath()` is needed so all types of file paths (relative and absolute) can be converted to a valid URL. I've re-added support for query strings back.
