### ISSUE TITLE
Nezobrazuje se Captcha

### ISSUE THREAD

**Issue by mirspan** [sunlight-cms/sunlight-cms#77]
V Bitnami wampstack-8.1.7-0 / php 8.1.7 se nezobrazuje Captach. GD rozšíření v php.ini povoleno.

**Comment by jDanek** [comment]
Problém je jen captchou nebo i ostatními obrázky? Captchu generuje PHP skript, pokud došlo k chybě ve skriptu tak se nevykresli.

**Comment by mirspan** [comment]
Na problém jsem zatím narazil jen v captchu. Nezobrazí se.

**Comment by ShiraNai7** [comment]
Prosím o konkrétní chybovou hlášku. Je ji možné zjistit zapnutím debug módu. V záložce "network" v dev tools prohlížeče by pak mělo být možné zjistit co je za problém.

**Comment by mirspan** [comment]
Unchecked runtime.lastError: The message port closed before a response was received.
index.php:1 

Error handling response: TypeError: self.processResponse is not a function
    at chrome-extension://cmkdbmfndkfgebldhnkbfhlneefdaaip/js/notification.js:154:10
index.php:65          

GET http://127.0.0.1/sl8/system/script/captcha/image.php?n=1 500 (Internal Server Error)

**Comment by jDanek** [comment]
Podle mého hledání se jedná o rozšíření prohlížeče `WhatRuns` a chyba je na jeho straně. Po nainstalování rozšíření vidím v devtool konzoli to samé i na Xamppu, ale captcha se normálně zobrazuje. Zakaž rozšíření pokud problém zmizí, není co řešit.

**Comment by mirspan** [comment]
To není tím WhatRuns jsem zkoušel deaktivovat a beze změn. Zkoušel jsem o i pod prohlížeči, v kterých nemám žádné rozšíření a beze změn.

**Comment by jDanek** [comment]
> Error handling response: TypeError: self.processResponse is not a function
> at chrome-extension://cmkdbmfndkfgebldhnkbfhlneefdaaip/js/notification.js:154:10

Já jsem psal, že tato chyba co uvádíš je problém na straně rozšíření prohlížeče. To co psal Shira jsi zkoušel? Co to vypisuje?

**Comment by ShiraNai7** [comment]
To chyba v JavaScript konzoli. Nás zajímá co vrací server na request `/system/script/captcha/image.php`, což bude v záložce network, jak jsem psal.

**Comment by mirspan** [comment]
Do konzole jsem se díval píšeto:

GET http://127.0.0.1/sl8/system/script/captcha/image.php?n=1 500 (Internal Server Error) 

Odkazuje to dál na index.php:65 .

Když se na ten řádek podívám obsahuje:
<td><input type='text' name='_cp' class='inputc' autocomplete='off'><img src='/sl8/system/script/captcha/image.php?n=1' alt='captcha' title='tyto znaky přepište do pole kontrola' class='cimage'><input type='hidden' name='_cn' value='1'></td>

**Comment by ShiraNai7** [comment]
Na ten request se dá kliknout a na pravé straně je pak vidět výstup.

**Comment by ShiraNai7** [comment]
Nemáme konkrétní chybovou hlášku tak prozatím zavírám. Můžeš issue znovu otevřít pokud se ti to podaří zjistit.
