### ISSUE TITLE
Funkce správa obsahu - skupina

### ISSUE THREAD

**Issue by mirspan** [sunlight-cms/sunlight-cms#78]
Doladit funkci správa obsahu - skupina. V jaké souvislosti se má používat. Nyní to není zřejmé.

**Comment by jDanek** [comment]
Typ `skupina` je ekvivalent původního `rozcestníku`. Dovoluje sloučit různé typy stránek a vypsat je stejně jako jsou vypisovány články v kategorii.

**Comment by mirspan** [comment]
Když vytvořím skupinu tak mě není jasné co dál s tím mám dělat. Čekal bych že budu něco ke skupině přiřazovat.

Když vepíšu do skupiny text tak na webu se text ukáže a pod ním se zobrazí text:   _Nenalezena žádná položka_.

**Comment by jDanek** [comment]
Předpokládám, že tohle úkol dokumentace.

**Comment by mirspan** [comment]
Do dokumentace a zvážit zda funkci poupravit aby byla srozumitelnější. Ono by stačilo do skupiny přidat funkci -> Přidat Kategorii.

**Comment by jDanek** [comment]
`Skupina` umožňuje sdružovat všechny typy a vykreslit jejich přehled. Tebou navrhované `přidat kategorii` nedává úplně smysl. Ve správě obsahu si u každého typu stránky můžeš zvolit její nadřazenou stránku, tam si právě volíš tu `skupinu`. Žádnou speciální funkci na to není potřeba.

**Comment by mirspan** [comment]
Přidat kategorii jsem uvedl jako příklad. Děkuji za vysvětlení.
