### ISSUE TITLE
Převést na rozšíření 

### ISSUE THREAD

**Issue by mirspan** [sunlight-cms/sunlight-cms#79]
Bylo by v hodné převést na rozšíření Fórum, Galerie a Kniha.

Zeštíhlil by CMS. Do budoucna by se Vám i lépe vyvíjely a přidávaly by se lepe nové funkce.

**Comment by jDanek** [comment]
Ono by se asi vyplatilo extrahovat obecně všechny příspěvky do samostatného pluginu. Ovšem bez dalšího refaktoringu systému to nepůjde.

**Comment by ShiraNai7** [comment]
Ve verzi 8 už se taková velká změna neplánuje, jinak nebude hotová v tomto století 🙂 Issue s dovolením zavírám, na případné další major verzi se bude pracovat v jiném repu.
