### ISSUE TITLE
Podpora Markdown

### ISSUE THREAD

**Issue by mirspan** [sunlight-cms/sunlight-cms#80]
Bylo by vhodné přidat nativní podporu Markdown [https://www.markdownguide.org](https://www.markdownguide.org).

**Comment by koca2000** [comment]
Uvažuji o vytvoření pluginu s [Easy MarkDown Editor](https://easy-markdown-editor.tk/).

**Comment by ShiraNai7** [comment]
To zní jako práce pro plugin 🙂
