### ISSUE TITLE
RSS v CMS

### ISSUE THREAD

**Issue by mirspan** [sunlight-cms/sunlight-cms#81]
V nastavení jsem nenašel povolení funkce RSS kanálu.

**Comment by jDanek** [comment]
RSS bylo ze systému odebráno, bude řešeno pluginem. Já ho rozpracovaný a bude následně uveřejněný na oficiálních stránkách a rovněž v komunitním projektu @friends-of-sunlight-cms

**Comment by ShiraNai7** [comment]
Jak píše Jirka, generování RSS bylo smazáno, není v plánu to mít v základu.
