### ISSUE TITLE
Podpora blokových editorů 

### ISSUE THREAD

**Issue by mirspan** [sunlight-cms/sunlight-cms#82]
Zvážit podporu blokového editoru [https://getcontenttools.com](https://getcontenttools.com).

**Comment by ShiraNai7** [comment]
Web a administrace jsou hodně oddělené a ten kód není zrovna znovupoužitelný 🍝 Pro nějaké jednoduché use-case to vypadá zajímavě, ale snažit se o 100% wysiwyg je cesta do pekel imo.
