### ISSUE TITLE
Podpora N1ED v TinyMCE & CKEditor

### ISSUE THREAD

**Issue by mirspan** [sunlight-cms/sunlight-cms#83]
Bylo by vhodné přidat podporu N1ED v TinyMCE & CKEditor [https://n1ed.com](https://n1ed.com).

**Comment by ShiraNai7** [comment]
Návrhy pluginů prosím až do nové diskuse, issues jsou pro problémy se samotným systémem.

Wysiwyg editory v základu nikdy nebyly, šlo by tedy o plugin. A ty už systém podporuje všechny (až je někdo napíše 🙂).
