### ISSUE TITLE
Chybí SMTP nastavení

### ISSUE THREAD

**Issue by mirspan** [sunlight-cms/sunlight-cms#84]
V nastavení chybí možnost si nastavit SMTP server.

**Comment by ShiraNai7** [comment]
Používá se nativní `mail()` funkce, takže se spoléhá na nastavení PHP, což je v drtivé většině případů dostačující.

Volání `Email::send()` lze přetížit přes event `mail.send`, takže je zde prostor pro pluginy řešit odesílání po svém (třeba pomocí nějaké knihovny).
