### ISSUE TITLE
Allow plugins to add assets anywhere in their code

### ISSUE THREAD

**Issue by koca2000** [sunlight-cms/sunlight-cms#93]
Currently the only way (that I found) to add assets like css or js files to the HTML head is to use the extend event `tpl.head` (and similar event for administration). However, at that moment the plugin may not know if the script or style is needed (e.g. codemirror style and script files are useless if there is no codemirror component on the page). Because of this, there may be a large amount of files that has to be downloaded and parsed even though they are useless. Therefore, it would be nice to have the ability to add css and js files as needed, perhaps using some static/global data structure that would then be used when the rendering of the head.

**Comment by jDanek** [comment]
I see what you're saying. I came across something similar with the reCaptcha plugin. There is no need to link assets to every page, just where the form is to be protected. Currently, one option is to add the necessary file to the output code. Another option is to condition the registration of the asset according to some criteria (page type, module id, ...)

As for WYSIWYG editors for example, there it is fine to put a CSS class `editor` on the textarea and it is solved. Of course, at the cost of the administration loading its assets everywhere, what if it was needed...

It sounds like an interesting idea to register assets in the registry and then call their collections where needed.

**Comment by Shira-3749** [comment]
Both the `tpl.head` and `admin.head` events happen after the main content has been already generated. This means you could register a listener for those events when you already know these assets will be needed. In any case - they get cached by the browser regardless, so I'm not sure if this optimalization is really needed. For big assets perhaps.

**Comment by koca2000** [comment]
Even a cached asset needs to be parsed and in the case of css it always calls redraw for each file. The idea of dynamic event registration on demand works. However, since it is a kind of tricky solution, I would suggest writing it into the documentation (once released).

**Comment by Shira-3749** [comment]
The issue with a simplistic approach is that plugins usually do more than register a few CSS/JS paths. For example, the built-in Lightbox plugin uses `tpl.head` / `admin.head` to add its CSS file, but also uses `tpl.body.end` / `admin.body.end` to load the JS and set some options (this doesn't need to be in `<head>`).

I've tried to solve this with enabling extend plugins to register events conditionally using the "group" option. See 4241b2c2bc23ed6f74fdf1d5c93eeb74c35d39ea how it is now used by the Lightbox plugin. This will be mentioned in the docs.
